apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: docker.io/library/nginx
    imagePullPolicy: Always
    name: nginx-cont
    ports:
    - containerPort: 80
      protocol: TCP
