apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: 'docker.io/library/fedora'
      command: ["/bin/sh","-c"]
      args: ["echo 'Hello World!'; cat"]
      tty: true
      stdin: true
