apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-prod
  name: nginx-prod-pod
  namespace: vt121170prj
spec:
  containers:
  - image: docker.io/library/nginx
    imagePullPolicy: Always
    name: nginx-cont
    ports:
    - containerPort: 80
      protocol: TCP
  serviceAccount: rodacomoroot
  serviceAccountName: rodacomoroot
