---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appvt121170
  name: appvt121170-svc
spec:
  ports:
  - name: appvt121170-svc-port
    port: 5000
    targetPort: 6000
  selector:
    app: appvt121170
