apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appvt121170

resources:
- ./Namespace/appvt121170.yaml
- ./HorizontalPodAutoscaler/appvt12117-hpa.yaml
- ./Service/appvt121170-svc.yaml
- ./BuildConfig/appvt121170-build.yaml
- ./ImageStream/appvt121170.yaml
- ./Deployment/appvt121170-deploy.yaml
- ./Route/appvt121170-route-2.yaml
- ./Route/appvt121170-route.yaml
