apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: vt121170prj
spec:
  containers:
  - image: nginxinc/nginx-unprivileged
    imagePullPolicy: Always
    name: nginx-cont
    ports:
    - containerPort: 8080
      protocol: TCP
