apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        imagePullPolicy: Always
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 8080
          protocol: TCP
