apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginxinc/nginx-unprivileged
    imagePullPolicy: Always
    name: nginx-cont
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: volume-html
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: volume-html
    configMap:
      name: html-config
