apiVersion: v1
kind: Pod
metadata:
  name: exemplo-pod
spec:
  volumes:
    - name: exemplo-volume
      persistentVolumeClaim:
        claimName: disco-pvc 
  containers:
    - name: container-um
      image: nginxinc/nginx-unprivileged
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: exemplo-volume
      ports:
      - containerPort: 8080

