apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nginx-app
  name: nginx-route
spec:
  host: nginx-app.apps.ocplab.vtal.intra
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nginx-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None

