---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: nginx
  name: nginx-is
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: docker.io/nginxinc/nginx-unprivileged
    importPolicy:
      scheduled: false

