apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: appteste
  name: appteste-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/marcos2soares/WORKSHOP-OPENSHIFT.git
    contextDir: REFERENCIA/app_source
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: appteste:latest
  triggers:
  - type: ConfigChange

