apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: appvt121170
  name: appvt121170
  namespace: vt121170prj
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/python-36
    referencePolicy:
      type: Source


