apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: appvt121170
  name: appvt121170v1
  namespace: vt121170prj
spec:
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: appvt121170:1.0
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy: {}
    type: Docker
