kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx-route
  labels:
    app: nginx
spec:
  host: 
  to:
    kind: Service
    name: nginx-svc
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: nginx
   app.kubernetes.io/part-of: nginx
 name: nginx-deploy
spec:
 replicas: 2
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - image: docker.io/library/nginx
       imagePullPolicy: Always
       name: nginx-cont
       ports:
       - containerPort: 80
         protocol: TCP
     serviceAccount: rodacomoroot
     serviceAccountName: rodacomoroot
