apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: 'random'
    haproxy.router.openshift.io/disable_cookies: 'true'
  labels:
    app: phyton-app
  name: phyton-app-route2
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: phyton-app-svc
    weight: 100
  port:
    targetPort: phyton-app-svc-port
  wildcardPolicy: None
